name: PHP Composer

on:
  workflow_dispatch:
        inputs:
            deploy_env:
                description: 'Deploy Environment'
                required: true
                default: 'stag'

permissions:
  contents: read

jobs:
  build:
    defaults:
      run:
        working-directory: web

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --no-progress

    - name: Build website
      env:
        SANITY_ID: ${{ secrets.SANITY_ID }}
        SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
      run: ./slowfoot build
      
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
